"""Added file type to the file model

Revision ID: d456dae9255c
Revises: 25402575183c
Create Date: 2024-01-25 18:47:34.517557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd456dae9255c'
down_revision = '25402575183c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
